# BASELINE — Non-negotiables ({{PROJECT_NAME}})

**One-page summary of the rules every implementation task must respect.** This file is the fast-load compass: read it at task start, cite which rules apply to your scope, and self-audit against it before declaring done.

> Generated by `/bootstrap-claude` on {{BOOTSTRAP_DATE}}. Refine with `/evolve-claude`.

For full architectural context, defer to:
{{PATTERN_DOC_REFERENCES}}
- `.claude/patterns/code-review-checklist.md` — full anti-pattern catalog with codes

---

## Project context (filled by the bootstrap)

- **Product:** {{PRODUCT_ONELINER}}
- **Primary persona:** {{PRIMARY_PERSONA}}
- **Domain:** {{DOMAIN}}
- **Default language:** {{DEFAULT_LANGUAGE}}

## Stack

| Layer | Tech |
|---|---|
{{STACK_TABLE}}

## Project layout

- **Main checkout path:** `{{MAIN_CHECKOUT_PATH}}`
- **Worktrees parent path:** `{{WORKTREES_PARENT_PATH}}`
- **Base branch:** `{{BASE_BRANCH}}`
- **Modules root(s):** {{MODULES_ROOTS}}
- **Package manager:** `{{PACKAGE_MANAGER}}`

## Commands

| Step | Command |
|---|---|
| Install deps | `{{INSTALL_CMD}}` |
| Type check | `{{TYPECHECK_CMD}}` |
| Lint | `{{LINT_CMD}}` |
| Format check | `{{FORMAT_CHECK_CMD}}` |
| Format write | `{{FORMAT_WRITE_CMD}}` |
| Unit tests | `{{UNIT_TEST_CMD}}` |
| E2E tests | `{{E2E_TEST_CMD}}` |

## Local files to seed (copied to new worktrees)

{{ENV_FILES_LIST}}

## Specialists configured

{{SPECIALISTS_LIST}}

## Integrations

{{INTEGRATIONS_LIST}}

---

## How to use this doc

Every specialist MUST do this at the start of every task:

1. Read this file fully (it is intentionally short).
2. **Load the spec** from `.claude/specs/<slug>/spec.md` (see § Spec discipline below). Print:
   > **Spec activated:** `.claude/specs/<slug>/spec.md` (Status: approved) — implementing § {{SECTIONS}}.
   > or `Spec activated: none — trivial fix waived by user.`
   > or `Spec activated: brief-only — /triage produced brief.md, no full spec.`
3. Output a one-line **Baseline activation** statement listing the rule IDs that apply to the current task.
   > **Baseline activated:** R1 ({{R1_SHORT}}), R6 ({{R6_SHORT}}), R10 ({{R10_SHORT}}). Out of scope: R12, R14.
4. Re-check the activated rules during the in-loop self-audit (see § BABYSIT loop below).
5. If a rule is genuinely impossible to apply, document the exception in the PR body — never silently violate it.

If you cannot tie at least 3 baseline rules to your task, you almost certainly missed scope.

---

## Spec discipline

**Policy:** `{{SPEC_POLICY}}` (`required` / `recommended` / `optional`).
**Location:** `{{SPEC_LOCATION}}` (default: `.claude/specs/`).
**Owner:** `{{SPEC_OWNER}}`.

Specs are the **contract** the implementation honors. Every non-trivial task gets a spec file on disk BEFORE code lands:

| Tool | Artifact | Size |
|---|---|---|
| `/triage` | `.claude/specs/<slug>/brief.md` | XS — single session |
| `/spec` | `.claude/specs/<slug>/spec.md` | S/M — default |
| `/architect` | `.claude/specs/<slug>/spec.md` (full) | L — new module / migration / sensitive surface |
| `/refine-spec <slug>` | updates existing spec | when reality educates the spec |

**Lifecycle:** `draft → approved → implementing → shipped`.

**Enforcement:** when `{{SPEC_POLICY}} = required`, the implementing specialist refuses to edit code unless `.claude/specs/<slug>/spec.md` exists with `Status: approved` (or the user explicitly waived with *"sem spec"*). The BABYSIT loop's L0 check restates which spec sections the diff implements, and L1.5 flags any file touched outside `## Scope § In`.

---

## DRY-first protocol (read BEFORE writing any new file)

Before creating ANYTHING new, walk this 5-question gate:

1. **Does a shared component / hook / utility already cover this?**
2. **Can the existing thing be extended (one extra prop, one extra method) instead of cloned?** Extension wins.
3. **If extension is impossible, is the new thing reusable?** Place it in `shared/` (or the project's equivalent) — never inside a feature module if any other module could need it.
4. **Did you grep for the same string / behavior in the codebase?** If 2+ files implement the same logic, consolidate before adding the third.
5. **Are you mirroring an existing pattern in style?** Naming, file layout, error-handling shape, response shape — copy the canonical reference module before improvising.

A new file that fails questions 1–3 is a code smell. Stop and reconsider.

---

## Baseline rules (cite by ID)

> The bootstrap generates an initial set of rules tailored to your stack. Add new rules as your project evolves (use `/evolve-claude` to promote recurring violations into BASELINE).

{{BASELINE_RULES_TABLE}}

---

## BABYSIT loop (during development)

Specialists do not "implement, then hand off and hope". They self-audit in a **5-level** tight loop before handoff. The first two (L0 / L1.5) anchor the loop to the spec; the rest enforce code quality.

1. **Activate baseline + spec** at start: cite the applicable rule IDs and the spec path (or document the trivial-fix waiver).
2. **Implement** the change.
3. **Level 0 — Spec citation (mandatory if a spec exists).**
   - Restate in one line which section(s) of the spec the diff implements:
     > **Spec coverage:** `.claude/specs/<slug>/spec.md` § 2 (Scope) + § 4 (Behavior contract). Out-of-scope additions: none.
   - If the diff went beyond `## In scope`, either trim the diff or run `/refine-spec <slug>` BEFORE the auditor. Silent scope creep is forbidden.
4. **Level 1 — `code-auditor` (mechanical, ~5s, max 3 iterations).**
   - List the files you touched (`git diff --name-only origin/{{BASE_BRANCH}}...HEAD`).
   - Invoke the `code-auditor` subagent (`Agent` tool, read-only). It greps the diff for known anti-pattern codes.
   - If Critical or High findings exist → fix in place → re-invoke. Up to 3 iterations.
   - After the third red iteration, escalate via `AskUserQuestion`.
5. **Level 1.5 — Spec-drift check (when a spec exists).**
   - The auditor walks `## Scope § In` of the spec against the diff's file list. Files modified that are **not** in `## In scope` raise an `S-C1` finding (out-of-spec drift).
   - Resolution: trim the diff OR update the spec via `/refine-spec <slug>` and re-run L1.
6. **Level 2 — `code-reviewer` (semantic, ~30s, max 2 iterations).**
   - Only after L1 + L1.5 are clean.
   - Invoke the `code-reviewer` subagent (`Agent` tool, read-only). The reviewer ALSO consumes the spec — it checks whether the implementation honors the `Behavior contract` and addresses the documented `Edge cases`.
   - If Critical or High findings exist → fix → re-invoke. Up to 2 iterations.
7. **Level 3 — `/duck-debug` (Rubber Duck Debugging, optional — only for M/L tasks).**
   - Only after levels 0–2 are clean.
   - **Skip** if the diff is trivial. **Run** if any of: ≥4 files; new module / repository / use case; domain modified; schema migration; auth / billing / multi-tenant / sensitive-data surface; cross-layer contract change.
8. **Handoff** to `/finish-task` only when all activated levels return clean.
9. **Telemetry** — every Critical/High finding the auditor or reviewer reports — and every gap the challenger confirms — is logged to `.claude/learning/violations.md`. Recurring violations get promoted into BASELINE, hooks, or knowledge entries (via `/evolve-claude`).

The five levels are complementary: spec anchoring (L0 + L1.5) catches scope drift; regex (L1) catches literal violations; senior judgment (L2) catches latent ones; verbalization (L3) catches unspoken assumptions.

---

## What this doc is NOT

- Not a tutorial. The patterns docs explain how to do things; this doc tells you what NOT to skip.
- Not exhaustive. Edge cases live in the code-review checklist.
- Not stable forever. When the same violation appears in `learning/violations.md` with high frequency, run `/evolve-claude` to promote the rule here.
