# Code Review Checklist — {{PROJECT_NAME}}

**The anti-pattern catalog.** Every entry has a code (`B-C1`, `F-H3`, `X-C2`, ...) that the auditor, reviewer, and hooks cite. Severity rubric: Critical (blocks merge) → High (should fix before merge) → Medium (recommended) → Low (nitpick).

> Generated by `/bootstrap-claude` on {{BOOTSTRAP_DATE}}. Add new codes via `/evolve-claude` as recurring violations are promoted.

---

## How to use this catalog

- **Auditor** (`.claude/agents/code-auditor.md`) reads this on every run and walks the codes mechanically.
- **Reviewer** (`.claude/agents/code-reviewer.md`) reads this and adds semantic judgment on top.
- **Hooks** (`.claude/hooks/post-edit-*.sh`) match a subset of these codes as grep regexes — fast, advisory, at write-time.
- **Implementers** cite the codes in PR descriptions when they intentionally accept a violation (`Accepting F-C3 here because…`).

## Code prefixes

- `B-*` — Backend
- `F-*` — Frontend
- `X-*` — Cross-cutting (env vars, migrations, contracts, secrets, AI)
- (Project may add new prefixes via `/evolve-claude` — e.g. `M-*` for mobile, `D-*` for data pipeline)

## Severity letters in code

- `Cn` — Critical
- `Hn` — High
- `Mn` — Medium
- `Ln` — Low

So `B-C1` is "Backend, Critical, #1"; `F-H3` is "Frontend, High, #3".

---

## File suffix → mandatory spec

The auditor checks for co-located test files using this mapping (filled by the bootstrap based on the project's testing convention):

{{SPEC_SUFFIX_TABLE}}

If the table above is empty, test coverage is not enforced for this project.

---

## Backend (B-*)

{{BACKEND_CHECKS}}

---

## Frontend (F-*)

{{FRONTEND_CHECKS}}

---

## Cross-cutting (X-*)

{{CROSS_CHECKS}}

---

## Proposed (not yet promoted)

When a recurring issue is spotted but does not yet have a code, the auditor / reviewer writes `(proposed)` in the report. Once the same `(proposed)` finding shows up ≥3 times in `.claude/learning/violations.md`, run `/evolve-claude` to promote it into a real code here.

{{PROPOSED_SECTION}}
