# Code Review Checklist — {{PROJECT_NAME}}

**The anti-pattern catalog.** Every entry has a code (`B-C1`, `F-H3`, `X-C2`, ...) that the auditor, reviewer, and hooks cite. Severity rubric: Critical (blocks merge) → High (should fix before merge) → Medium (recommended) → Low (nitpick).

> Generated by `/bootstrap-claude` on {{BOOTSTRAP_DATE}}. Add new codes via `/evolve-claude` as recurring violations are promoted.

---

## How to use this catalog

- **Auditor** (`.claude/agents/code-auditor.md`) reads this on every run and walks the codes mechanically.
- **Reviewer** (`.claude/agents/code-reviewer.md`) reads this and adds semantic judgment on top.
- **Hooks** (`.claude/hooks/post-edit-*.sh`) match a subset of these codes as grep regexes — fast, advisory, at write-time.
- **Implementers** cite the codes in PR descriptions when they intentionally accept a violation (`Accepting F-C3 here because…`).

## Code prefixes

- `B-*` — Backend
- `F-*` — Frontend
- `X-*` — Cross-cutting (env vars, migrations, contracts, secrets, AI)
- `S-*` — Spec-driven (drift between the diff and the approved spec — universal, not stack-specific)
- (Project may add new prefixes via `/evolve-claude` — e.g. `M-*` for mobile, `D-*` for data pipeline)

## Severity letters in code

- `Cn` — Critical
- `Hn` — High
- `Mn` — Medium
- `Ln` — Low

So `B-C1` is "Backend, Critical, #1"; `F-H3` is "Frontend, High, #3".

---

## File suffix → mandatory spec

The auditor checks for co-located test files using this mapping (filled by the bootstrap based on the project's testing convention):

{{SPEC_SUFFIX_TABLE}}

If the table above is empty, test coverage is not enforced for this project.

---

## Backend (B-*)

{{BACKEND_CHECKS}}

---

## Frontend (F-*)

{{FRONTEND_CHECKS}}

---

## Cross-cutting (X-*)

{{CROSS_CHECKS}}

---

## Spec-driven (S-*)

Universal codes — they don't depend on stack. Active only when a spec file exists for the task at `.claude/specs/<slug>/spec.md`.

### S-C1 — Critical — Out-of-spec drift

**What it catches.** A file in the diff is not listed under the spec's `## Scope § In` (or `§ 6 Files § Modify/Create`).
**Why it's Critical.** Silent scope creep breaks the SDD contract — the spec is no longer the source of truth, and reviewers / future devs lose the audit trail.
**How to fix.** Either trim the diff back to the spec's scope, or run `/refine-spec <slug>` to update the spec BEFORE re-running the auditor. Document the decision under § 9 Decisions of the spec.
**Auditor behavior.** Walk the diff's file list. For each path not present under § 2 In OR § 6 Files, emit one `S-C1` finding citing `path` and the closest matching scope bullet (or "no related scope bullet").

### S-H1 — High — Behavior contract not honored

**What it catches.** The diff doesn't visibly implement one of the imperatives in `## Behavior contract`.
**Why it's High.** A spec's `Behavior contract` is the executable subset of the spec — every bullet should map to a code change or a test. Missing means either incomplete work or a documentation gap.
**How to fix.** Add the missing implementation OR move the imperative to a follow-up spec and trim § 4 here.

### S-H2 — High — Edge case unaddressed

**What it catches.** An edge case listed in `## Edge cases that probably bite` has no corresponding test, guard, or comment in the diff.
**Why it's High.** Edge cases listed in the spec were called out for a reason. Skipping them in code = vibe coding.
**How to fix.** Add the test/guard, or document under § 9 Decisions why the edge case is no longer a concern.

### S-M1 — Medium — Spec links not updated

**What it catches.** Spec § 10 Links has `PR:` empty or `Status` is still `draft`/`approved` at finish-task time.
**How to fix.** `/finish-task` updates these automatically; if it failed, do it manually.

---

## Proposed (not yet promoted)

When a recurring issue is spotted but does not yet have a code, the auditor / reviewer writes `(proposed)` in the report. Once the same `(proposed)` finding shows up ≥3 times in `.claude/learning/violations.md`, run `/evolve-claude` to promote it into a real code here.

{{PROPOSED_SECTION}}
