# {{PROJECT_NAME}} — Agent Manifest

> Industry-standard `AGENTS.md` pointer recognized by Claude Code, Cursor, Codex, Aider, and most agentic coding tools. Bootstrapped from [`claude-setup`](https://github.com/natanrotta/claude-setup) and tuned to this project.
>
> **For agents:** treat `.claude/CLAUDE.md` as the canonical contract — it's loaded automatically by Claude Code and supersedes anything in this file. This file exists so tools that don't natively read `.claude/` still find the same orientation.

---

## Project

- **One-liner:** {{PRODUCT_ONELINER}}
- **Persona:** {{PRIMARY_PERSONA}}
- **Domain:** {{DOMAIN}}
- **Conversation language:** `{{CONVERSATION_LANGUAGE}}`
- **Base branch:** `{{BASE_BRANCH}}`

## Stack

{{STACK_BADGES_PLAINTEXT}}

## How to work in this repo

1. **Read first.** `.claude/CLAUDE.md` (lifecycle contract) and `.claude/patterns/BASELINE.md` (non-negotiables) are mandatory pre-reads at the start of every task.
2. **Spec-Driven.** Spec policy is **`{{SPEC_POLICY}}`**. For non-trivial tasks under `required` or `recommended`, write `.claude/specs/<slug>/spec.md` BEFORE touching code (via `/spec`, `/triage`, or `/architect`).
3. **Self-audit loop.** Implementing specialists run the BABYSIT loop (L0 spec citation → L1 mechanical auditor → L1.5 spec-drift → L2 semantic reviewer → L3 rubber-duck for M/L tasks) before handing off.
4. **Telemetry.** Critical/High findings logged to `.claude/learning/violations.md`. Recurring violations get promoted via `/evolve-claude`.

## Specialists

{{SPECIALISTS_LIST}}

## Commands

| Command | Purpose |
|---|---|
| `/triage <task>` | Lightweight 3-perspective pre-dev brief |
| `/spec <slug>: <task>` | 1-page spec on disk for S/M tasks |
| `/architect <feature>` | Full spec with field research for L tasks |
| `/brainstorm <idea>` | Divergent design exploration |
| `/start-task` | Open worktree + branch for the task |
| `/check` | Type + lint + format + test loop |
| `/finish-task` | Coverage → review → check → PR |
| `/code-review` | Independent semantic review |
| `/normalize <target>` | Read-only audit against patterns |
| `/duck-debug` | Rubber-duck dialogue for M/L work |
| `/evolve-claude` | Refine `.claude/` from telemetry + drift |

## Pre-flight checklist for agents

Before writing any code, confirm out loud:

- [ ] **Baseline activated:** R-IDs from `BASELINE.md` that apply.
- [ ] **Spec activated:** path to `.claude/specs/<slug>/spec.md` (or `brief.md`, or explicit waiver).
- [ ] **Knowledge activated:** entries from `.claude/knowledge/<specialist>.md`.
- [ ] **Violations radar:** recent codes from `.claude/learning/violations.md`.

If any of these is missing and the task is non-trivial, STOP and resolve it before editing.

---

## Why this file is short

Agentic tools need a quick, scannable orientation. The deep wiring — lifecycle phases, BABYSIT details, specialist prompts, hook regexes, anti-pattern catalog — lives in `.claude/`. Read it from there.

> Generated by `/bootstrap-claude` on {{BOOTSTRAP_DATE}}.
